### ISSUE TITLE
Tab problem - Scroll View Count Error

### ISSUE THREAD

**Issue by koushik16github** [DUBULEE/CoordinatorLayoutHelper#1]
I want to add 5 tab but, when I'm scrolling in 4 and 5 no. tab, app is crashed, 1, 2, 3 is running well.

Crash reposrts:
=============================================
com.github.dubulee.coordinatorlayouthelpersample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                Process: com.github.dubulee.coordinatorlayouthelpersample, PID: 1168
                                                                                                java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                                                                    at com.github.dubulee.coordinatorlayouthelper.HeaderLayoutBehavior.onNestedPreScroll(HeaderLayoutBehavior.java:167)
                                                                                                    at com.github.dubulee.coordinatorlayouthelper.HeaderLayoutBehavior.onNestedPreScroll(HeaderLayoutBehavior.java:15)
                                                                                                    at android.support.design.widget.CoordinatorLayout.onNestedPreScroll(CoordinatorLayout.java:1513)
                                                                                                    at android.support.v4.view.ViewParentCompatLollipop.onNestedPreScroll(ViewParentCompatLollipop.java:70)
                                                                                                    at android.support.v4.view.ViewParentCompat$ViewParentCompatLollipopImpl.onNestedPreScroll(ViewParentCompat.java:184)
                                                                                                    at android.support.v4.view.ViewParentCompat.onNestedPreScroll(ViewParentCompat.java:355)
                                                                                                    at android.support.v4.view.NestedScrollingChildHelper.dispatchNestedPreScroll(NestedScrollingChildHelper.java:208)
                                                                                                    at android.support.v7.widget.RecyclerView.dispatchNestedPreScroll(RecyclerView.java:8665)
                                                                                                    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2380)
                                                                                                    at android.view.View.dispatchTouchEvent(View.java:9297)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2769)
                                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                                    at android.view.View.dispatchPointerEvent(View.java:9517)
                                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
                                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
                                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
                                                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
                                                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
                                                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6072)
                                                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                                                    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                                	at android.view.InputEvent

**Comment by DUBULEE** [comment]
Hi~ Koushik Debnath.
Thanks for your interest.

I didn't show this error.
Please, More detail ... (ex: Reproduction path)
I'll find a way to modify.

I tested..  added 5 tabs.  It was normal.
````java

private void setupViewPager(ViewPager viewPager) {
        final PagerAdapter pagerAdapter = new PagerAdapter(getSupportFragmentManager());
        pagerAdapter.addFragment(ListViewPageFragment.createInstance(), "List View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");
        pagerAdapter.addFragment(ListViewPageFragment.createInstance(), "List View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");

        viewPager.setAdapter(pagerAdapter);
    }
````

I have a question. 
Did you use CoordinatorLayoutHelperRecyclerView or NestedScrollView ??

You check this.. and Related code -> HeaderLayoutBehavior.java
````java
private void findHeaderLayout(ViewGroup rootViewGroup) {
        if (null != mScrollViewList && mScrollViewList.size() > 0) {
            mScrollViewList.clear();
        }
        for (int z = 0; z < rootViewGroup.getChildCount(); z++) {
            View view = (View) rootViewGroup.getChildAt(z);
            if (view instanceof CoordinatorLayoutHelperRecyclerView) {
                mScrollViewList.add(((CoordinatorLayoutHelperRecyclerView) rootViewGroup.getChildAt(z)));
            }
            else if (view instanceof NestedScrollView) {
                mScrollViewList.add(((NestedScrollView) rootViewGroup.getChildAt(z)));
            }
        }

    }
````

Please Check and see that part~ :)
Fell free to contact me.
Thanks. 

Best regards,
DUBU LEE

**Comment by koushik16github** [comment]
Hello DUBU LEE,
I've used the same code, but there is the same problem.

private void setupViewPager(ViewPager viewPager) {
        final PagerAdapter pagerAdapter = new PagerAdapter(getSupportFragmentManager());
        pagerAdapter.addFragment(ListViewPageFragment.createInstance(), "List View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");
        pagerAdapter.addFragment(ListViewPageFragment.createInstance(), "List View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");
        pagerAdapter.addFragment(GridViewPageFragment.createInstance(), "Grid View");

        viewPager.setAdapter(pagerAdapter);
    }


Crash reports:
=================================
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                              Process: com.github.dubulee.coordinatorlayouthelpersample, PID: 659
                                                                                              java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                                                  at com.github.dubulee.coordinatorlayouthelper.HeaderLayoutBehavior.onNestedPreScroll(HeaderLayoutBehavior.java:167)
                                                                                                  at com.github.dubulee.coordinatorlayouthelper.HeaderLayoutBehavior.onNestedPreScroll(HeaderLayoutBehavior.java:15)
                                                                                                  at android.support.design.widget.CoordinatorLayout.onNestedPreScroll(CoordinatorLayout.java:1513)
                                                                                                  at android.support.v4.view.ViewParentCompatLollipop.onNestedPreScroll(ViewParentCompatLollipop.java:70)
                                                                                                  at android.support.v4.view.ViewParentCompat$ViewParentCompatLollipopImpl.onNestedPreScroll(ViewParentCompat.java:184)
                                                                                                  at android.support.v4.view.ViewParentCompat.onNestedPreScroll(ViewParentCompat.java:355)
                                                                                                  at android.support.v4.view.NestedScrollingChildHelper.dispatchNestedPreScroll(NestedScrollingChildHelper.java:208)
                                                                                                  at android.support.v7.widget.RecyclerView.dispatchNestedPreScroll(RecyclerView.java:8665)
                                                                                                  at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2380)
                                                                                                  at android.view.View.dispatchTouchEvent(View.java:9297)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:2769)
                                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                                  at android.view.View.dispatchPointerEvent(View.java:9517)
                                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
                                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
                                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
                                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
                                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
                                                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
                                                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
                                                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6072)
                                                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                                                  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                              	at android.view.InputEventR

Now what should I do?

**Comment by DUBULEE** [comment]
Hi~ 

hum... 
Please, Let me know Reproduction path.

Added five tab... and .. Just Scroll??

**Comment by koushik16github** [comment]
yeah I've added 5 tab and scroll it normal way

**Comment by DUBULEE** [comment]
hummmm.... 

Did you edit HeaderLayoutBehavior.java?? 

Would you show me HeaderLayoutBehavior.java:167 LIne Info?

**Comment by DUBULEE** [comment]
oh!! I find it ... Let me see...

**Comment by koushik16github** [comment]
Okay

**Comment by koushik16github** [comment]
if (!mIsScrolling) {
            mSkippedOffset += dy;

            if (Math.abs(mSkippedOffset) >= mTouchSlop) {
                mIsScrolling = true;
                target.getParent().requestDisallowInterceptTouchEvent(true);
            }
        }

The last brace is HeaderLayoutBehavior.java:167

**Comment by koushik16github** [comment]
Hello DUBULEE,
Are you there? Is there any solution???

**Comment by DUBULEE** [comment]
I am fixing it.. 

I see this problem.. but.. not easy edit

**Comment by DUBULEE** [comment]
If you are busy , use it (https://github.com/DUBULEE/FixedScrollLayout)

**Comment by koushik16github** [comment]
ok

**Comment by DUBULEE** [comment]
I fix it !! 

I will push~!!!

**Comment by DUBULEE** [comment]
I pushed it !!

Check Please~~ 

Thanks :+1:  :)

**Comment by koushik16github** [comment]
ok thanks DUBU LEE
